# / / / / / / / /|\ \ \ \ \ \ \ #
# | ChestShopDB Configuration | #
# \ \ \ \ \ \ \ \|/ / / / / / / #

# Add newly created shops to database
# true | false
newshops: true

# Add old shops to database
# true | false
oldshops: true

# Database system
# MySQL | SQLite
dbsystem: SQLite

# # # # # # # # # # # # # # #
# # # Database Settings # # #

# Database name
# In the case of SQLite, this will be the file name
database: minecraft

# MySQL server settings
# [!] Ignore these if using SQLite [!] #
username: bukkit
password: password
host: localhost
port: 3306